### ISSUE TITLE
[OpenIDModule] Activity is not logged

### ISSUE THREAD

**Issue by Glandos** [simpleid/simpleid#29]
I'm a bit new to the code, but it seems that dynamically registered clients and activity for the OpenID 2 protocol are put into `$user` object (see [adding activity](https://github.com/simpleid/simpleid/blob/master/www/core/Protocols/OpenID/OpenIDModule.php#L876) and [remembering client](https://github.com/simpleid/simpleid/blob/master/www/core/Protocols/OpenID/OpenIDModule.php#L899)).

However, the `saveUser()` call at the end does simply nothing. It uses the `user:write` store, without default, so nothing is stored in my case. But even with a defined store, the default implementation just [ignores writes](https://github.com/simpleid/simpleid/blob/master/www/core/Store/DefaultStoreModule.php#L94). So nothing is stored and nothing can be displayed later.

**Comment by kelvinmo** [comment]
`saveUser()` is meant to use the `user_cfg:write` store by default, as the default file-based StoreModule does not support writes to the identity directory.  However because `getStores()` in `DefaultStoreModule` is returning `user:default` rather than `user:read`, it's thinking that it is supporting `user:write`.

So the solution should be fixing [this line](https://github.com/simpleid/simpleid/blob/6258dbef030592df65ca659e6a81f9482e1361e5/www/core/Store/DefaultStoreModule.php#L57) to return `user:read` rather than `user:default`.
