### ISSUE TITLE
still alive?

### ISSUE THREAD

**Issue by petrk94** [simpleid/simpleid#30]
Hello,
I would like to know whether simpleid is still alive?
Due the last release is from 2016, but here on github the last commit was 2 months ago, so I dont know what I should think about it :/ 
I would like to use OpenID, but somehow the development is nearly everywhere frozen...
Thanks

**Comment by kelvinmo** [comment]
The latest release on the web site is SimpleID 1.0.2.  The SimpleID 1.x series support the original OpenID spec (versions 1 and 2).  As both specs are now deprecated, this series of SimpleID is no longer maintained, apart from serious security fixes.

The one currently on git is the SimpleID 2.x series.  It supports OpenID Connect, which is the latest version of the OpenID protocol.  It *should* be working, but it has not been extensively tested.  Sadly I have been very busy with other things over the last period, so I am spending less time on it as I would like.

**Comment by petrk94** [comment]
Oh I see :/ 
thats really sad, due I got it yesterday run successful and could connect it with Wordpress to login there.
What you need for help? Unfortunately Im not such deep in programming, but maybe help on another way?
SimpleID 2 is talked on the website documentation, but no link to the latest build. Maybe worth to fix this information that its here on github.
If it would be helpful, I can make a draft manual in markdown and write down the steps to get simpleid 2 running. But I would need sometimes help by you.
Let me know what you think
Thanks

**Comment by agentcobra** [comment]
same issue for me (see #24)

**Comment by petrk94** [comment]
@agentcobra , Im using a openid plugin, no sso plugin with oAuth functionality like you used. 
Even thought about to set up a own oauth provider, but it seems more complicated rather openid

**Comment by kelvinmo** [comment]
SimpleID 2 is actually documented here: http://simpleid.koinic.net/docs/2/.  For the old OpenID protocol, you can find further instructions on how to set it up on SimpleID 2 here: http://simpleid.koinic.net/docs/2/openid/.

This is not linked from the web site as the software is not released yet.

**Comment by petrk94** [comment]
@kelvinmo is there any way that someone can help you? Or do you need money for working on it? There are few open source funding platforms.

**Comment by strk** [comment]
Do you not accept issues for SimpleID-1 ? I'm having issues with PHP7... could provide a patch (is there a branch for it?)

**Comment by strk** [comment]
I filed my bug for version 1 in #34

**Comment by petrk94** [comment]
Yes, with PHP7 it has really issues, the variable like @@version@@ are showed when I log in. In general it work, but it even the SimpleID2 version is not working well. I really would wish the developer would be more active or tell what he need so we can support, spread the word etc.
Im not a friend of simple donation without knowing that the project continues.
I decided to try to develop a own identity service and see how its possible to extend it to openid

**Comment by strk** [comment]
@petrk94 do you know if there's a branch for the simpleID2 version ? That's all I'm interested in for now, could fork and continue maintainance there ...

**Comment by petrk94** [comment]
@strk I think the master branch is the 2 Version, you can switch the branches between 0.8, 0.9, simpleid1 and master. Therefore this seems to be the current one

**Comment by kelvinmo** [comment]
Sorry for the late reply, but I am currently overseas.

At this stage, my changing life commitments means that it is unlikely that I will have time to perform major work on SimpleID (other than critical security fixes) into the foreseeable future.  From time to time there may be commits to the master branch on the very rare occasion when I have time to work on it.

In relation the SimpleID 1, it should be noted that the protocols this version implements - OpenID versions 1 and 2 - are officially deprecated in favour of OpenID Connect.  Therefore, as stated in the [announcement](https://simpleid.org/releases/simpleid-1.0/), there won't be any work done to this branch, apart from critical security fixes.

The world of federated identity has moved on since OpenID 1 and SimpleID was conceived.  Back then the vision was that everyone can run an authentication server (using software such as SimpleID).  These days federated identity is now concentrated on the big players (Google, Facebook, etc) and corporates, due to the need to exchange security credentials out-of-band.  This means that "amateurs" are effectively locked out of the federated identity ecosystem, which renders the need for software such as SimpleID more and more redundant.

**Comment by strk** [comment]
Thanksforthe update @kelvinmo -- I think the Internet is what we make of it, so whether SimpleID is useful or not depends on how many services we enable to accept OpenID. I've "recently" (2017?) implemented OpenID-2.0 support in Gitea, for example. You can login via SimpleID in http://gitea.com

OpenID-Connect seems to be harder to do wrt to using an arbitrary URL but I've understood the specifications do allow that, with some extension (self-discovery, is it called?). Does SimpleID implement that ? Do you know of websites accepting self-hosted OpenID-Connect authentication ?

**Comment by kelvinmo** [comment]
> OpenID-Connect seems to be harder to do wrt to using an arbitrary URL but I've understood the specifications do allow that, with some extension (self-discovery, is it called?). 

Yes - it's a combination of the [Discovery](http://openid.net/specs/openid-connect-discovery-1_0.html) and [Dynamic Registration](http://openid.net/specs/openid-connect-registration-1_0.html) extensions that provide similar arbitary URL functionality in OpenID 2

> Does SimpleID implement that ? 

The master branch implements the Dynamic Registration extension (see www/core/Protocols/OpenID/Extensions/SRegOpenIDExtensionModule.php).  The Discovery extension is meant to be implemented by OpenID clients rather than servers, so it's not implemented by SimpleID.  However I have a library (https://github.com/kelvinmo/simplewebfinger) that implements the WebFinger protcol, upon which the Discovery extension is based.

> Do you know of websites accepting self-hosted OpenID-Connect authentication ?

No.  All the sites I know that uses OpenID Connect use the major social networks (Google, Facebook, Yahoo) as the authentication service.

**Comment by strk** [comment]
Gitea deployments could be in such a list, if we handle to implement it (do you want to help?):
https://github.com/go-gitea/gitea/issues/1299

**Comment by pawel-kow** [comment]
@strk, right now ID4me tries to make the efforts to open Single-Sign On solutions in a federated way.
It's also based on OpenID Connect, just a discovery function is done over DNS instead of Webfinger, which makes the user experience a way better.
Actually I plan to try out installing SimpleID 2 to see if it works out of the box.

@petrk94, are there some particular features which you missed in SimpleID 2 or problems you faced? Just asking before I start playing around with it...

**Comment by petrk94** [comment]
@pawel-kow in general, I only got SimpleID 1 work correctly. SimpleID 2 is not good enough documented to understand its way of function so you might be see by your own where the issues will happen, due its not finished, there is no tutorial or instruction available. https://simpleid.org/docs/2/

**Comment by jorsn** [comment]
Nextcloud also supports custom OpenID Connect logins, but I think it doesn't implement audo-discovery.

**Comment by petrk94** [comment]
@jorsn 
Thats true, I got SimpleID 1 work well with Nextcloud, but the username generation in Nextcloud didnt looked nice and as said, SimpleID 2 is not this what I want to run, furthermore I started in the past the development of a own kind system with the benefits of OpenID, but so far, it doesn would pay my bills, so other projects have priority :/
